<?php include_once( VIEWS_PATH . 'partials/navbar.phtml'); ?>
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3"><?php echo APP_NAME; ?></h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem ut molestiae earum voluptate quos, at totam fugiat pariatur! Quas nemo dolorum delectus enim rerum. Veniam tenetur dolore maxime quo exercitationem?
      Qui totam laboriosam, fuga velit voluptate iure neque recusandae necessitatibus illum fugiat praesentium dicta, voluptas non, itaque commodi similique eaque quo? Molestiae neque quaerat ipsum cum pariatur similique, mollitia magnam!
      Aliquid voluptatum ullam, illum totam dicta maxime similique porro perspiciatis eligendi rerum? Id dignissimos sed assumenda blanditiis? Ipsa possimus, ipsum debitis quas adipisci harum, consequatur maiores, commodi dolores error amet!</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>
    <hr>
  </div> <!-- /container -->
</main>