<nav class="navbar navbar-expand-lg navbar-dark bg-primary" id="navbarMain">
  <div class="container">
    <a class="navbar-brand" href="#">  <?php if (!(empty(APP_BRAND))): ?>
      <img src="<?php echo APP_BRAND; ?>" alt="<?php echo APP_NAME; ?>" width="50" height="50">
    <?php elseif (!empty(APP_ICON)): ?>
      <i class="<?php echo APP_ICON; ?>" aria-hidden="true"></i>
    <?php endif; ?>
    <?php echo APP_NAME; ?></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTop">
      <ul class="navbar-nav ml-auto">
        <?php foreach($links as $link): ?>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $link['href']; ?>"><?php echo $link['text']; ?></a>
        </li>
        <?php endforeach;?>       
        </ul>       
    </div>
  </div>
</nav>