<nav class="navbar navbar-expand-lg navbar-dark bg-primary" id="navbarMain">
  <div class="container">
    <a class="navbar-brand" href="#">  <?php if (!(empty(APP_BRAND))): ?>
      <img src="<?php echo APP_BRAND; ?>" alt="<?php echo APP_NAME; ?>" width="50" height="50">
    <?php elseif (!empty(APP_ICON)): ?>
      <i class="<?php echo APP_ICON; ?>" aria-hidden="true"></i>
    <?php endif; ?>
    <?php echo APP_NAME; ?></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTop">
      <ul class="navbar-nav ml-auto">
        <?php foreach($links as $link): ?>
          <?php if ($link['subitems']): ?>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="<?php echo $link['id'] ?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?php echo $link['text']; ?></a>
            <div class="dropdown-menu" aria-labelledby="<?php echo $link['id'] ; ?>">
                <?php foreach($link['subitems'] as $sub): ?>
                <a class="dropdown-item" href="<?php echo $sub['href']; ?>"><?php echo $sub['text']; ?></a>
                <?php endforeach; ?>
            </div>
          <?php else: ?>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $link['href']; ?>"><?php echo $link['text']; ?></a>
        </li>

        <?php endif; endforeach; ?>       
            
        </li>
      </ul>
     
    </div>
  </div>
</nav>